version: "2"
run:
  modules-download-mode: readonly
linters:
  enable:
    - misspell
    - revive
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/praveengongada/catalyst
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
